name: rrule_generator
description: RRuleGenerator is a widget for generating recurrence rules, such as described in the iCalendar RFC
version: 0.3.0
homepage: https://www.jelter.net
repository: https://github.com/tkortekaas/rrule_generator

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: '>=0.17.0 <0.19.0'